Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,18 +25,23 @@ jobs:
           scp -i github-deploy-key.pem scrap.py ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/scrap.py
           scp -i github-deploy-key.pem service_providers.json ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/service_providers.json
 
-      - name: Install dependencies on EC2
+      - name: Install dependencies and create virtual environment on EC2
         run: |
           ssh -i github-deploy-key.pem -t ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+            set -e  # Stop if any command fails
             sudo apt update
             sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-venv unzip chromium-browser
             wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
             unzip -o chromedriver_linux64.zip
             sudo mv chromedriver /usr/local/bin/
             rm chromedriver_linux64.zip
+            
             # Set up virtual environment
-            python3 -m venv ~/myenv
+            if [ ! -d "~/myenv" ]; then
+              python3 -m venv ~/myenv
+            fi
             source ~/myenv/bin/activate
+            pip install --upgrade pip
             pip install selenium webdriver-manager
           EOF
 
