Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,18 +31,26 @@ jobs:
             sudo apt update
             sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-venv unzip chromium-browser
             wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
-            unzip chromedriver_linux64.zip
+            unzip -o chromedriver_linux64.zip
             sudo mv chromedriver /usr/local/bin/
             rm chromedriver_linux64.zip
             # Set up virtual environment
-            python3 -m venv myenv
-            source myenv/bin/activate
+            python3 -m venv ~/myenv
+            source ~/myenv/bin/activate
             pip install selenium webdriver-manager
           EOF
 
       - name: Run script on EC2
         run: |
-          ssh -i github-deploy-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'source ~/myenv/bin/activate && python3 /home/ubuntu/scrap.py'
+          ssh -i github-deploy-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+            if [ -d "~/myenv" ]; then
+              source ~/myenv/bin/activate
+              python3 /home/ubuntu/scrap.py
+            else
+              echo "Virtual environment not found. Exiting."
+              exit 1
+            fi
+          EOF
 
       - name: Retrieve output file from EC2
         run: |
